services:
  web:
    build:
      context: .
      args:
        APP_NAME: django_crm
    environment:
      - DBHOST=db
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 your_project.wsgi:application"
  
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: bottlecrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5